// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvEMpG43Et3hHPmR7zLHQNoGEmYHri9Ts',
    appId: '1:166276047527:web:0c1f87554f583e8e06f182',
    messagingSenderId: '166276047527',
    projectId: 'notewave-72cbe',
    authDomain: 'notewave-72cbe.firebaseapp.com',
    storageBucket: 'notewave-72cbe.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPx0CyplDH8KQqq3J1eZzCiN-eZ6DiDN4',
    appId: '1:166276047527:android:9a719a6b811888a106f182',
    messagingSenderId: '166276047527',
    projectId: 'notewave-72cbe',
    storageBucket: 'notewave-72cbe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZw9imE5a20EgFV5bKgk0Uhm7JrXo3DWI',
    appId: '1:166276047527:ios:4a6d51808ccf45d506f182',
    messagingSenderId: '166276047527',
    projectId: 'notewave-72cbe',
    storageBucket: 'notewave-72cbe.appspot.com',
    iosBundleId: 'com.asa.noteWave',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZw9imE5a20EgFV5bKgk0Uhm7JrXo3DWI',
    appId: '1:166276047527:ios:1725847f8cae9f5c06f182',
    messagingSenderId: '166276047527',
    projectId: 'notewave-72cbe',
    storageBucket: 'notewave-72cbe.appspot.com',
    iosBundleId: 'com.asa.noteWave.RunnerTests',
  );
}
